include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.chopper.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"

linter:
  rules:
    non_constant_identifier_names: false
    prefer_const_constructors: false
    sort_pub_dependencies: false
